### ISSUE TITLE
The required client_id parameter was not provided

### ISSUE THREAD

**Issue by petamcgee** [GrantQuick/BlackbaudSkyApi#1]
Hi there, I'm getting this error when trying to connect my Power BI desktop the the Sky Api:

The required client_id parameter was not provided

Any suggestions?

Thanks,
Peta

**Comment by GrantQuick** [comment]
Hi Peta, did you add your client_id to the appropriate file and include the updated file in the mez?

**Comment by GrantQuick** [comment]
Issue closed - client_id not added to client_id file.
