### ISSUE TITLE
Invalid client error

### ISSUE THREAD

**Issue by pedrodude** [GrantQuick/BlackbaudSkyApi#3]
Followed your procedure, but seem to be getting an "invalid_client", "The specified credentials were not valid." error (same, as described here: https://developer.blackbaud.com/skyapi/docs/authorization/common-auth-issues#requesting-tokens) immediately after authorizing the custom app with Blackbaud.

Any ideas?  The client ID, secret, and API keys are all correct.

Kind regards,

**Comment by GrantQuick** [comment]
Can you confirm that the three files in the mez contain the correct keys? Assuming they do, the connection can't really fail (providing there are no issues at Blackbaud's end).

**Comment by GrantQuick** [comment]
Unable to replicate, closing ticket.
