### ISSUE TITLE
#4 on ReadMe Instructions

### ISSUE THREAD

**Issue by nbaskett** [GrantQuick/BlackbaudSkyApi#4]
GrantQuick, I'm a newbie here, and sorry if this is an utterly dumb question:

When you say...
"Open up SkyApi.zip. Edit the client_id, client_secret and api_subscription_key files. In each file, copy and paste the character strings for the appropriate entity (the client_id, client_secret and api_subscription_key generated when creating a Blackbaud developer account and app) into the correct file. Save the changes to each of the three files."

...How does one edit these three files?

**Comment by esmartt** [comment]
Hi Nbaskett - you can edit these files with a text editor like notepad

**Comment by GrantQuick** [comment]
nbaskett - Graham Getty has expanded upon the readme [here](https://resolvedllc.com/blackbaud-sky-custom-connector-power-bi/), which you may find useful.
