### ISSUE TITLE
Data.Source error

### ISSUE THREAD

**Issue by mnagbebet** [GrantQuick/BlackbaudSkyApi#6]
Hey I received the following error message. Do you any idea how I can correct this?

DataSource.Error: Web.Contents failed to get contents from 'https://api.sky.blackbaud.com/opportunity/v1/opportunities?include_inactive=true&limit=5000' (400): Bad Request
Details:
    DataSourceKind=RENXT
    DataSourcePath=RENXT
    Url=https://api.sky.blackbaud.com/opportunity/v1/opportunities?include_inactive=true&limit=5000

Kind Regards

**Comment by GrantQuick** [comment]
Is this issue still ocuuring for you? It's possible that there was a temporary problem with that endpoint at Blackbaud.

**Comment by GrantQuick** [comment]
No response, can't replicate, closing ticket
